### ISSUE TITLE
[ADDING] Some Customation Options

### ISSUE THREAD

**Issue by RAtwood90** [exochron/ToyBoxEnhanced#48]
Hello Mate! Also here great Job on this Addon!

Still missing some things if it's possible to add these?

1. Hiding Achievement Points and Using Random Favorite Toy Button and "Usable" Text.
2. Your Mount Journal is perfectly skinned for ElvUI Users. Possible u can do it for ToyBox also?
Put u two Screenshots in this Post for you to see the difference what i mean.

![image](https://github.com/exochron/ToyBoxEnhanced/assets/73589071/643c8955-14f1-44bf-883f-df940ccd5d23)

![image](https://github.com/exochron/ToyBoxEnhanced/assets/73589071/2c8ba38d-d4cf-4361-9732-4b5feab3b5f7)

Thank you!

**Comment by RAtwood90** [comment]
@exochron is that possible for you to make it? 
Like it works for your MountJournalEnhanced?

Thank you <3

**Comment by exochron** [comment]
hi and sorry for the late reply. I somehow missed some notifications >.<

First, the reason the missing option was that in my opinion these are some main features of the addon. Hiding them and keeping the original progress bar would basically just look like the original UI.
But, I'm a fan of customization and giving proper options to the user. So I'm going to add some option for that. :)

As for ElvUI: that has been requested quite a lot and I'd love to add some visual compatibility. But, there is a technical reason/barrier for that. In short: Toys can be used in fight. So every related UI element is way more restricted and prone to taint errors. That's why the filters are also not working while in fight. I'm using a trick to get around it a bit. But that is also the reason why the Toybox is not styled properly by ElvUI.

**Comment by RAtwood90** [comment]
> hi and sorry for the late reply. I somehow missed some notifications >.<
> 
> First, the reason the missing option was that in my opinion these are some main features of the addon. Hiding them and keeping the original progress bar would basically just look like the original UI. But, I'm a fan of customization and giving proper options to the user. So I'm going to add some option for that. :)
> 
> As for ElvUI: that has been requested quite a lot and I'd love to add some visual compatibility. But, there is a technical reason/barrier for that. In short: Toys can be used in fight. So every related UI element is way more restricted and prone to taint errors. That's why the filters are also not working while in fight. I'm using a trick to get around it a bit. But that is also the reason why the Toybox is not styled properly by ElvUI.

I don't get it why you getting Taints and ElvUI not by Skinning?

Cause of the Features of your Addon?

And then u add a Skin into your Addon for ElvUI Users? 
Then ElvUI is detected?

Regards and thanks for replying back!

**Comment by RAtwood90** [comment]
@exochron sorry to bother you again and asking to reply on that thank you! <3

**Comment by exochron** [comment]
Alright, lets dive a bit into WoWs interface.
There are 2 major concepts to prevent addons or macros from combat automation (or botting). It's secure code and code tainting.
Secure code contains basically everything provided by Blizzard. This code is signed and has more privileges like changing UI elements while in combat. Most cast buttons are such elements or in our case toy buttons.
All other code is considered insecure. Insecure code cannot call certain functions or change UI elements freely. (Thats the error: "Addon action blocked.") That applies to all user addons. When an addon tries to modify a secure element or variable, it becomes tainted. Even following secure code parts become tainted as well. That code taint can spread quite easily. The DropdownMenus are notorious examples for such taint spreader. (As author it's also quite hard to replicate and fix these kind of errors.)
So in order to avoid all that I basically build a second layer with own toy buttons on top of the default UI. It looks exactly the same like the original, but I can manipulate it freely as long as it's not in combat.
But that trick only works because there is a background texture which covers all original UI buttons. If I would make that background transparent like in ElvUI you would actually see the original and addon buttons overlapping.

You might be wondering why it's working for mounts then. Mounts can not be used in combat. So mount buttons are not that much restricted and I can modify them freely. Toys on the other hand can be used in combat and therefor are toy buttons more restricted.

**Comment by RAtwood90** [comment]
> Alright, lets dive a bit into WoWs interface. There are 2 major concepts to prevent addons or macros from combat automation (or botting). It's secure code and code tainting. Secure code contains basically everything provided by Blizzard. This code is signed and has more privileges like changing UI elements while in combat. Most cast buttons are such elements or in our case toy buttons. All other code is considered insecure. Insecure code cannot call certain functions or change UI elements freely. (Thats the error: "Addon action blocked.") That applies to all user addons. When an addon tries to modify a secure element or variable, it becomes tainted. Even following secure code parts become tainted as well. That code taint can spread quite easily. The DropdownMenus are notorious examples for such taint spreader. (As author it's also quite hard to replicate and fix these kind of errors.) So in order to avoid all that I basically build a second layer with own toy buttons on top of the default UI. It looks exactly the same like the original, but I can manipulate it freely as long as it's not in combat. But that trick only works because there is a background texture which covers all original UI buttons. If I would make that background transparent like in ElvUI you would actually see the original and addon buttons overlapping.
> 
> You might be wondering why it's working for mounts then. Mounts can not be used in combat. So mount buttons are not that much restricted and I can modify them freely. Toys on the other hand can be used in combat and therefor are toy buttons more restricted.

Yeah, i know all that. The only thing i wondered was why can ElvUI Skin it but you can't it like that way cause i didn't know. 
That you created a second Layer to avoiding this.

And what is then you are creating a ElvUI Skin for Users with ElvUI?

Easy and Quick Solution for this and working in that Way you work.

Black Background to Hide the Default UI.
And then going like ElvUI with the Borders in Quality Color and White Font Text?

Should work cause you are hiding the Default UI with a pure Black Background right?
If you got Time for that to do it.
All ElvUI User would say thank you for that <3

Have a Nice Day! Stay Healthy Keep your Great Attidude and Work you are awesome! 
Lovely Addons!

If you want and needing a Favor i can Remix Boost your Alts through HC Dungeons let me know ^^

**Comment by exochron** [comment]
ElvUI support was added with version 2.25.
I hope you like it. :)

**Comment by AngelosNaoumis** [comment]
![image](https://github.com/user-attachments/assets/023e3306-f74f-433d-b704-2551e06a3192)
hello what should I do to activate it? as I just get black background

**Comment by AngelosNaoumis** [comment]
Could you please also remove the border around this?
![image](https://github.com/user-attachments/assets/08c5a518-9974-4952-ad65-aac8efd29047)

e.g. from pet Journal
![image](https://github.com/user-attachments/assets/9698a475-d554-4e68-9f84-d340f51637cc)

**Comment by RAtwood90** [comment]
> ElvUI support was added with version 2.25. I hope you like it. :)

Yeah, looks sick could you also remove the Fancy Art Left/Right in ElvUI Version?
![image](https://github.com/user-attachments/assets/b57c92f5-b443-4570-a405-551ff7497698)
